# Generated by Django 5.2.4 on 2025-07-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='program',
            field=models.CharField(blank=True, choices=[('GCC', 'GCC'), ('HOTEL_MANAGEMENT', 'Hotel Management'), ('NURSING', 'Nursing'), ('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters'), ('ESTEP', 'E-step'), ('PVP', 'PVP')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('WALK_IN', 'Walk In'), ('ON_HOLD', 'On Hold'), ('REGISTERED', 'Registered')], default='ENQUIRY', max_length=15),
        ),
    ]
