# Generated by Django 5.2.4 on 2025-07-31 07:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_program_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded to Processing'), ('ACCEPTED', 'Accepted by Processing'), ('PROCESSING', 'In Processing'), ('COMPLETED', 'Processing Completed'), ('REJECTED', 'Processing Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='document_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('VERIFIED', 'Verified'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='documents_received',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='processing_executive',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROCESSING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='processing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded to Processing'), ('ACCEPTED', 'Accepted by Processing'), ('PROCESSING', 'In Processing'), ('COMPLETED', 'Processing Completed'), ('REJECTED', 'Processing Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='processing_status_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADM_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority'], name='leads_lead_priorit_ddce28_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['processing_status'], name='leads_lead_process_39b111_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='leads_lead_assigne_3f8857_idx'),
        ),
        migrations.AddField(
            model_name='processingupdate',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processingupdate',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_updates', to='leads.lead'),
        ),
    ]
