# Generated by Django 5.2.4 on 2025-08-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_processingupdate_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='program',
            field=models.CharField(blank=True, help_text='Enter the program name', max_length=100, null=True),
        ),
    ]
