# Generated by Django 5.2.4 on 2025-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('WEBSITE', 'Website'), ('WALK_IN', 'Walk-in'), ('AUTOMATION', 'automation'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
