# Generated by Django 5.2.4 on 2025-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or comments about the lead', null=True),
        ),
    ]
