# Generated by Django 5.2.4 on 2025-10-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_remarkhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.TextField(default='ENQUIRY', help_text='Current status of the lead'),
        ),
    ]
