# Generated by Django 5.2.4 on 2025-10-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='program',
            field=models.CharField(blank=True, help_text='Enter the program name', max_length=2000, null=True),
        ),
    ]
