# Generated by Django 5.2.4 on 2025-11-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='drive_link',
            field=models.URLField(blank=True, help_text='Google Drive folder link for student materials', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text="Student's email address", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Student's phone number", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(blank=True, choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('ONLINE', 'Online')], help_text='Class type for the student', max_length=10, null=True),
        ),
    ]
