# Generated by Django 5.2.4 on 2025-11-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_alter_student_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('NO_SESSION', 'No Session')], default='PRESENT', max_length=15)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='trainers.student')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='trainers.trainer')),
            ],
            options={
                'ordering': ['-date', 'student__name'],
                'indexes': [models.Index(fields=['date', 'trainer'], name='trainers_at_date_c68493_idx')],
                'unique_together': {('date', 'student')},
            },
        ),
    ]
