# Generated by Django 5.2.4 on 2025-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('A1', 'A1 (Beginner)'), ('A2', 'A2 (Elementary)'), ('B1', 'B1 (Intermediate)'), ('B2', 'B2 (Upper Intermediate)'), ('A1 ONLINE', 'A1 (Online)'), ('A2 ONLINE', 'A2 (Online)'), ('B1 ONLINE', 'B1 (Online)'), ('B2 ONLINE', 'B2 (Online)'), ('A1 EXAM PREPERATION', 'A1 (Exam Preparation)'), ('A2 EXAM PREPERATION', 'A2 (Exam Preparation)'), ('B1 EXAM PREPERATION', 'B1 (Exam Preparation)'), ('B2 EXAM PREPERATION', 'B2 (Exam Preparation)')], max_length=200),
        ),
    ]
