# Generated by Django 5.2.4 on 2025-10-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hob', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
