# Generated by Django 5.2.4 on 2025-11-10 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
