# Generated by Django 5.2.7 on 2025-11-15 05:12

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_penalty_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=50)),
                ('document', cloudinary.models.CloudinaryField(help_text='Upload attendance document (PDF, image, etc.)', max_length=255, verbose_name='Attendance Document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Attendance Document',
                'verbose_name_plural': 'Attendance Documents',
                'ordering': ['-date'],
            },
        ),
    ]
