# Generated by Django 5.2.7 on 2025-11-15 05:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Document Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('month', models.CharField(max_length=100, verbose_name='Month')),
                ('document', cloudinary.models.CloudinaryField(blank=True, help_text='Upload attendance document (PDF, Excel, Image, etc.)', max_length=255, null=True, verbose_name='Attendance Document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Document',
                'verbose_name_plural': 'Attendance Documents',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
