# Generated by Django 5.2.4 on 2025-10-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'General Manager'), ('OPS', 'Operations Manager'), ('ADM_MANAGER', 'Admission Manager'), ('ADM_EXEC', 'Admission Executive'), ('PROCESSING', 'Processing Executive'), ('MEDIA', 'Media Team'), ('TRAINER', 'Trainer'), ('BUSINESS_HEAD', 'Business Head')], max_length=20),
        ),
    ]
