# Generated by Django 5.2.4 on 2025-10-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='heading',
            field=models.CharField(default='red', help_text='Brief summary of your daily report', max_length=300, verbose_name='Report Heading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='name',
            field=models.CharField(default='red', help_text='Give a title to your daily report', max_length=200, verbose_name='Report Name'),
            preserve_default=False,
        ),
    ]
