# Generated by Django 5.2.4 on 2025-10-28 08:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_dailyreport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='attached_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload any relevant file (optional)', max_length=255, null=True, verbose_name='Attached File'),
        ),
    ]
