# Generated by Django 5.2.7 on 2025-10-28 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_dailyreport_attached_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Title of the micro work', max_length=200, verbose_name='Job Title')),
                ('description', models.TextField(help_text='Detailed description of the work', verbose_name='Description')),
                ('time_required', models.CharField(help_text='Estimated time required (e.g., 2 hours, 30 minutes)', max_length=100, verbose_name='Time Required')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_works', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Micro Work',
                'verbose_name_plural': 'Micro Works',
                'ordering': ['-created_at'],
            },
        ),
    ]
