# Generated by Django 5.2.4 on 2025-10-29 04:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_microwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='microwork',
            name='work_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
