# Generated by Django 5.2.4 on 2025-10-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_microwork_work_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microwork',
            name='work_date',
        ),
    ]
